### ISSUE TITLE
Install issue 04_type_scalar.t tests fail on win32

### ISSUE THREAD

**Issue by mwss** [daoswald/Inline-CPP#39] opened 2016-08-03 13:12 UTC
Following the installation receipt on https://github.com/wbraswell/rperl/blob/master/INSTALL , cpan fails to install RPerl on Win32 with MinGW64 /Strawberry Perl / g++ (x86_64-posix-sjlj, built by strawberryperl.com project) 4.9.2.
With RPerl-1.7 the test hang forever on 03_inline_cpp.t   13/16 
With RPerl-2.0 the 04_type_scalar.t tests will fail:
"Non-existent or undefined Perl config value $Config{long longsize}, croaking at C:\STRAWB~1\cpan\build\RPerl-
2-0\blib\lib/RPerl/HelperFunctions_cpp.pm line 51."
# 

"C:\Strawberry\perl\bin\perl.exe" -MExtUtils::Command -e cp -- script/rperl blib\script\rperl
pl2bat.bat blib\script\rperl
  WBRASWELL/RPerl-2.000000.tar.gz
  C:\STRAWB~1\c\bin\dmake.exe -- OK
Running make test
"C:\Strawberry\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')" t/
*.t
t/00_depend.t .................. ok
t/01_changes.t ................. ok
t/02_inline_c.t ................ ok
t/03_inline_cpp.t .............. ok
t/04_type_scalar.t ............. 1/310 ERROR ERPTYREI02: Non-existent or undefined Perl config value $Config{long longsize}, croaking at C:\STRAWB~1\cpan\build\
RPerl-2-0\blib\lib/RPerl/HelperFunctions_cpp.pm line 51.
INIT failed--call queue aborted.
# Looks like your test exited with 255 just after 4.

t/04_type_scalar.t ............. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 306/310 subtests
t/05_type_array.t .............. 1/232 ERROR ERPTYREI02: Non-existent or undefined Perl config value $Config{long longsize}, croaking at C:\STRAWB~1\cpan\build\
RPerl-2-0\blib\lib/RPerl/HelperFunctions_cpp.pm line 51.
INIT failed--call queue aborted.
# Looks like your test exited with 255 just after 2.

t/05_type_array.t .............. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 230/232 subtests
t/06_type_hash.t ............... 1/247 ERROR ERPTYREI02: Non-existent or undefined Perl config value $Config{long longsize}, croaking at C:\STRAWB~1\cpan\build\
RPerl-2-0\blib\lib/RPerl/HelperFunctions_cpp.pm line 51.
INIT failed--call queue aborted.
# Looks like your test exited with 255 just after 2.

t/06_type_hash.t ............... Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 245/247 subtests
t/07_type_gmp.t ................ You tried to plan twice at t/07_type_gmp.t line 33.
BEGIN failed--compilation aborted at t/07_type_gmp.t line 42.
t/07_type_gmp.t ................ Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 75/75 subtests
t/09_interpret_execute.t ....... ERROR ERPTYREI02: Non-existent or undefined Perl config value $Config{long longsize}, croaking at C:\STRAWB~1\cpan\build\RPerl-
2-0\blib\lib/RPerl/HelperFunctions_cpp.pm line 51.
INIT failed--call queue aborted.
t/09_interpret_execute.t ....... Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run
t/10_precompiled_oo_inherit.t .. 2/251 ERROR ERPTYREI02: Non-existent or undefined Perl config value $Config{long longsize}, croaking at C:\STRAWB~1\cpan\build\
RPerl-2-0\blib\lib/RPerl/HelperFunctions_cpp.pm line 51.
INIT failed--call queue aborted.
# Looks like your test exited with 255 just after 16.

t/10_precompiled_oo_inherit.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 235/251 subtests
t/11_precompiled_sort.t ........ 1/254 ERROR ERPTYREI02: Non-existent or undefined Perl config value $Config{long longsize}, croaking at C:\STRAWB~1\cpan\build\
RPerl-2-0\blib\lib/RPerl/HelperFunctions_cpp.pm line 51.
INIT failed--call queue aborted.
# Looks like your test exited with 2 just after 11.

t/11_precompiled_sort.t ........ Dubious, test returned 2 (wstat 512, 0x200)
Failed 243/254 subtests
t/12_parse.t ................... ERROR ERPTYREI02: Non-existent or undefined Perl config value $Config{long longsize}, croaking at C:\STRAWB~1\cpan\build\RPerl-
2-0\blib\lib/RPerl/HelperFunctions_cpp.pm line 51.
INIT failed--call queue aborted.
t/12_parse.t ................... Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run
t/13_generate.t ................ ERROR ERPTYREI02: Non-existent or undefined Perl config value $Config{long longsize}, croaking at C:\STRAWB~1\cpan\build\RPerl-
2-0\blib\lib/RPerl/HelperFunctions_cpp.pm line 51.
INIT failed--call queue aborted.
t/13_generate.t ................ Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run
## Test Summary Report

t/04_type_scalar.t           (Wstat: 65280 Tests: 4 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 310 tests but ran 4.
t/05_type_array.t            (Wstat: 65280 Tests: 2 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 232 tests but ran 2.
t/06_type_hash.t             (Wstat: 65280 Tests: 2 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 247 tests but ran 2.
t/07_type_gmp.t              (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 75 tests but ran 0.
t/09_interpret_execute.t     (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/10_precompiled_oo_inherit.t (Wstat: 65280 Tests: 16 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 251 tests but ran 16.
t/11_precompiled_sort.t      (Wstat: 512 Tests: 11 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 254 tests but ran 11.
t/12_parse.t                 (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/13_generate.t              (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=13, Tests=91, 44 wallclock secs ( 0.08 usr +  0.03 sys =  0.11 CPU)
Result: FAIL
Failed 9/13 test programs. 0/91 subtests failed.
dmake.exe:  Error code 255, while making 'test_dynamic'
  WBRASWELL/RPerl-2.000000.tar.gz
  C:\STRAWB~1\c\bin\dmake.exe test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports WBRASWELL/RPerl-2.000000.tar.gz
Stopping: 'install' failed for 'RPerl'.
Failed during this command:
 WBRASWELL/RPerl-2.000000.tar.gz              : make_test NO
#

**Comment by wbraswell** [comment] 2016-08-04 07:57
@mwss 
I think this is an RPerl issue and should probably have been filed as an issue on the RPerl GitHub repo:
https://github.com/wbraswell/rperl

However, I think this issue can be solved by using the latest RPerl code from GitHub instead of the CPAN code, because bulk88 and I have fixed many Windows issues over the last few weeks, after RPerl v2.0 was released on CPAN.

Please perform the same installation recipe, but this time do steps 0, 1C, 2B:
https://github.com/wbraswell/rperl/blob/master/INSTALL

Meanwhile, I suggest this issue be closed because I don't think it belongs on this repo.

bulk88 and I are usually available online to chat via IRC:
irc.perl.org #perl11

**Comment by bulk88** [comment] 2016-09-07 00:36
This ticket has nothing to do with I::CPP. It was an rperl bug that was fixed, this ticket should be closed.

**Comment by bulk88** [comment] 2016-09-07 00:38
This ticket has nothing to do with I::CPP. It was an rperl bug that was fixed, this ticket should be closed.

**Comment by daoswald** [comment] 2017-01-25 05:50
Closing per bulk88's comment that this issue is not caused by Inline::CPP.

**Closed by daoswald** 2017-01-25 05:50 UTC
