### ISSUE TITLE
Windows Strawberry Failure, t/classes/07conflict_avoid.t

### ISSUE THREAD

**Issue by wbraswell** [daoswald/Inline-CPP#30] opened 2015-07-05 23:27 UTC
cpanm (App::cpanminus) 1.7027 on perl 5.020002 built for MSWin32-x86-multi-thread-64int
Work directory is C:\DOCUME~1\stefanos/.cpanm/work/1436135735.2208
You have make C:\Strawberry\c\bin\dmake.exe
You have LWP 6.13
Falling back to Archive::Tar 2.04
Searching RPerl on cpanmetadb ...
--> Working on RPerl
Fetching http://www.cpan.org/authors/id/W/WB/WBRASWELL/RPerl-1.000001.tar.gz
-> OK
Unpacking RPerl-1.000001.tar.gz
Entering RPerl-1.000001
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.04)
Configuring RPerl-1.000001
Running Makefile.PL
Warning: prerequisite Inline::CPP 0.63 not found.
Checking if your kit is complete...
Looks good
Generating a dmake-style Makefile
Writing Makefile for RPerl
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Inline::CPP 0.63 ... No
Checking if you have ExtUtils::MakeMaker 7.04 ... Yes (7.04)
Checking if you have Inline 0.76 ... Yes (0.80)
Checking if you have Test::Exception 0.32 ... Yes (0.36)
Checking if you have Module::Refresh 0.17 ... Yes (0.17)
Checking if you have Inline::C 0.76 ... Yes (0.76)
Checking if you have PadWalker 2.1 ... Yes (2.1)
Checking if you have Parse::Eyapp 1.182 ... Yes (1.182)
Checking if you have Perl::Tidy 20140711 ... Yes (20140711)
Checking if you have Inline::Filters 0.17 ... Yes (0.17)
Checking if you have Perl::Critic 1.121 ... Yes (1.125)
==> Found dependencies: Inline::CPP
Searching Inline::CPP on cpanmetadb ...
--> Working on Inline::CPP
Fetching http://www.cpan.org/authors/id/D/DA/DAVIDO/Inline-CPP-0.71.tar.gz
-> OK
Unpacking Inline-CPP-0.71.tar.gz
Entering Inline-CPP-0.71
Checking configure dependencies from META.json
Checking if you have FindBin 0 ... Yes (1.51)
Checking if you have ExtUtils::CppGuess 0.07 ... Yes (0.09)
Checking if you have ExtUtils::MakeMaker 7.04 ... Yes (7.04)
Checking if you have Config 0 ... Yes (5.020002)
Configuring Inline-CPP-0.71
Running Makefile.PL
What C++ compiler would you like to use? [g++ -xc++] g++ -xc++
What default libraries would you like to include? [-lstdc++] -lstdc++
Detected <iostream> style headers. ('.h' not needed.)
Checking if your kit is complete...
Looks good
Generating a dmake-style Makefile
Writing Makefile for Inline::CPP
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Test::More 1.001009 ... Yes (1.001014)
Checking if you have Carp 0 ... Yes (1.3301)
Checking if you have Parse::RecDescent 0 ... Yes (1.967009)
Checking if you have File::Temp 0 ... Yes (0.2304)
Checking if you have Config 0 ... Yes (5.020002)
Checking if you have English 0 ... Yes (1.09)
Checking if you have Inline 0.78 ... Yes (0.80)
Checking if you have Inline::C 0.67 ... Yes (0.76)
Building and testing Inline-CPP-0.71
cp lib/Inline/CPP.pm blib\lib\Inline\CPP.pm
cp lib/Inline/CPP.pod blib\lib\Inline\CPP.pod
cp lib/Inline/CPP/Parser/RecDescent.pm blib\lib\Inline\CPP\Parser\RecDescent.pm
cp lib/Inline/CPP/Config.pm blib\lib\Inline\CPP\Config.pm
"C:\Strawberry\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef _Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')" t/_.t t/_/_.t
# $Config{osname}:     MSWin32
# $Config{cc}:         gcc
# $Config{gccversion}: 4.8.3
t/00load_prereqs.t .................... ok
t/01fn_cans.t ......................... ok
t/02basic.t ........................... ok
t/03prefix.t .......................... ok
t/04charptr.t ......................... ok
t/05pod.t ............................. skipped: Author Test: Set $ENV{RELEASE_TESTING} to a true value to run.
t/06fn_regress.t ...................... ok
t/07perlcritic.t ...................... skipped: Author Test: Set $ENV{RELEASE_TESTING} to a true value to run.
# 
# Compiler guesses:
#  EU::CppGuess:    [g++ -xc++],
#  Old Makefile.PL: [g++].
# Linker guesses:
#  EU::CppGuess:    [-lstdc++],
#  Old Makefile.PL: [-lstdc++].
t/08cppguess.t ........................ ok
t/09pod_coverage.t .................... skipped: Author Test: Set $ENV{RELEASE_TESTING} to a true value to run.
t/10kwalitee.t ........................ skipped: Author Test: Set $ENV{RELEASE_TESTING} to a true value to run.
t/11rewrite_config.t .................. skipped: Author Test: Set $ENV{RELEASE_TESTING} to a true value to run.
t/12custom_libs.t ..................... ok
t/13version_numbers.t ................. skipped: Author Test: Set $ENV{RELEASE_TESTING} to a true value to run.
t/14changes.t ......................... skipped: Author tests skipped.  Set $ENV{RELEASE_TESTING} to run
t/15config_case.t ..................... ok
t/classes/01empty_ns_is_main.t ........ ok
t/classes/02main_ns_is_main.t ......... ok
t/classes/03baz_ns_is_baz.t ........... ok
t/classes/04invoke_from_non_main.t .... ok
t/classes/05invalid_classes.t ......... ok
t/classes/06inherit.t ................. ok
Unrecognized escape \D passed through at (eval 12) line 3.
Unrecognized escape \s passed through at (eval 12) line 3.
Unrecognized escape \T passed through at (eval 12) line 3.

#   Failed test 'Foo::Bar::MyClass->can('new')'
#   at t/classes/07conflict_avoid.t line 71.
#     Foo::Bar::MyClass->can('new') failed

#   Failed test 'Foo::Bar::MyClass->new() died'
#   at t/classes/07conflict_avoid.t line 73.
#     Error was:  Can't locate object method "new" via package "Foo::Bar::MyClass" (perhaps you forgot to load "Foo::Bar::MyClass"?) at C:/Strawberry/perl/lib/Test/More.pm line 690.

#   Failed test 'Our "MyClass" is a "Foo::Bar::MyClass"'
#   at t/classes/07conflict_avoid.t line 75.
#          got: ''
#     expected: 'Foo::Bar::MyClass'

#   Failed test 'Foo::Qux::MyClass->can('new')'
#   at t/classes/07conflict_avoid.t line 77.
#     Foo::Qux::MyClass->can('new') failed

#   Failed test 'Foo::Qux::MyClass->new() died'
#   at t/classes/07conflict_avoid.t line 79.
#     Error was:  Can't locate object method "new" via package "Foo::Qux::MyClass" (perhaps you forgot to load "Foo::Qux::MyClass"?) at C:/Strawberry/perl/lib/Test/More.pm line 690.

#   Failed test 'Our "MyClass" is a "Foo::Qux::MyClass"'
#   at t/classes/07conflict_avoid.t line 81.
#          got: ''
#     expected: 'Foo::Qux::MyClass'
Can't call method "fetch" on an undefined value at t/classes/07conflict_avoid.t line 83.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 6.
t/classes/07conflict_avoid.t .......... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 6/6 subtests 
t/classes/08auto.t .................... ok
t/classes/09auto_mixed.t .............. ok
t/classes/10auto_inherit.t ............ ok
t/grammar/00pod_coverage.t ............ skipped: Test::Pod::Coverage 1.00 required for testing POD coverage
t/grammar/01nherit.t .................. ok
t/grammar/02scope.t ................... ok
t/grammar/03inline.t .................. ok
t/grammar/04const.t ................... ok
t/grammar/05virt.t .................... ok
t/grammar/06deflt.t ................... ok
t/grammar/07static.t .................. ok
t/grammar/08anon.t .................... ok
t/grammar/09purevt.t .................. ok
t/grammar/10struct.t .................. ok
t/grammar/11minhrt.t .................. ok
t/grammar/12retlst.t .................. ok
t/grammar/13vararg.t .................. ok
t/grammar/14const.t ................... ok
t/grammar/15stvar.t ................... ok
t/grammar/16varlst.t .................. ok
t/grammar/17memberarray.t ............. ok
t/grammar/18namespace.t ............... ok
t/grammar/19multidimarray.t ........... ok
t/namespace/01empty_ns_is_main.t ...... ok
t/namespace/02main_ns_is_main.t ....... ok
t/namespace/03baz_ns_is_baz.t ......... ok
t/namespace/04invoke_from_non_main.t .. ok
t/namespace/05invalid_ns.t ............ ok
t/namespace/06inherit.t ............... ok
## Test Summary Report

t/08cppguess.t                      (Wstat: 0 Tests: 2 Failed: 0)
  TODO passed:   2
t/classes/07conflict_avoid.t        (Wstat: 65280 Tests: 6 Failed: 6)
  Failed tests:  1-6
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/grammar/11minhrt.t                (Wstat: 0 Tests: 38 Failed: 0)
  TODO passed:   23-24, 27-28, 30, 32
Files=52, Tests=269, 249 wallclock secs ( 0.09 usr +  0.23 sys =  0.32 CPU)
Result: FAIL
Failed 1/52 test programs. 6/269 subtests failed.
dmake.exe:  Error code 255, while making 'test_dynamic'
-> FAIL Installing Inline::CPP failed. See C:\DOCUME~1\stefanos.cpanm\work\1436135735.2208\build.log for details. Retry with --force to force install it.
-> FAIL Installing the dependencies failed: Module 'Inline::CPP' is not installed
-> FAIL Bailing out the installation for RPerl-1.000001.

**Comment by daoswald** [comment] 2015-07-05 23:37
Additional questions:

Is this a 32b or 64b Perl build? What version of Windows?

Also, would it be possible for someone who has such a failure state to grab this repo, and run "perl Makefile.PL", "make", "make test" .... and then paste the entire make test output?  There may be more information that 'cpanm' could be squelching.

I haven't been able to replicate the issue using a clean strawberry install on a 32b Win7 installation.  Obviously that doesn't suggest others are not having issues.  But it would help me if I knew how to make this happen.

**Comment by bulk88** [comment] 2015-07-06 00:51
Try building Inline::CPP in a directory with a space in it.

**Comment by ToApolytoXaos** [comment] 2015-07-06 08:13
@wbraswell thank you for opening a ticket for this problem of mine.

This issue happened on my Windows XP SP3 with Strawberry Perl 5.20.2 32-bit (of course), using **`cpanm RPerl`** command. Obviously the spaces between *C:\Documents and Settings\* is causing a parsing issue.

I'm currently testing it with **`cpan RPerl`** to see whether it reproduces the same output, but this time with Strawberry Perl 5.22.1. Thus far, it seems to compile properly; if something breaks, I will of course come back to report it.

**Comment by ToApolytoXaos** [comment] 2015-07-06 10:20
OK, I have tried `cpan RPerl` as I have mentioned before, but it breaks again.

`t\classes\07conflict_avoid.t` causes problems from line 71 to 81.

```
can_ok 'Foo::Bar::MyClass', 'new';

my $fb = new_ok 'Foo::Bar::MyClass';

is ref($fb), 'Foo::Bar::MyClass', 'Our "MyClass" is a "Foo::Bar::MyClass"';

can_ok 'Foo::Qux::MyClass', 'new';

my $fq = new_ok 'Foo::Qux::MyClass';

is ref($fq), 'Foo::Qux::MyClass', 'Our "MyClass" is a "Foo::Qux::MyClass"';
```

Here's the error messages:
```
t/classes/07conflict_avoid.t .......... 1/? #   Failed test 'Foo::Bar::MyClass->can('new')'
#   at t/classes/07conflict_avoid.t line 71.
#     Foo::Bar::MyClass->can('new') failed

#   Failed test 'Foo::Bar::MyClass->new() died'
#   at t/classes/07conflict_avoid.t line 73.
#     Error was:  Can't locate object method "new" via package "Foo::Bar::MyClass" (perhaps you forgot to load "Foo::Bar::MyClass"?) at C:/Strawberry/perl/lib/Test/More.pm line 690.

#   Failed test 'Our "MyClass" is a "Foo::Bar::MyClass"'
#   at t/classes/07conflict_avoid.t line 75.
#          got: ''
#     expected: 'Foo::Bar::MyClass'

#   Failed test 'Foo::Qux::MyClass->can('new')'
#   at t/classes/07conflict_avoid.t line 77.
#     Foo::Qux::MyClass->can('new') failed

#   Failed test 'Foo::Qux::MyClass->new() died'
#   at t/classes/07conflict_avoid.t line 79.
#     Error was:  Can't locate object method "new" via package "Foo::Qux::MyClass" (perhaps you forgot to load "Foo::Qux::MyClass"?) at C:/Strawberry/perl/lib/Test/More.pm line 690.

#   Failed test 'Our "MyClass" is a "Foo::Qux::MyClass"'
#   at t/classes/07conflict_avoid.t line 81.
#          got: ''
#     expected: 'Foo::Qux::MyClass'
Can't call method "fetch" on an undefined value at t/classes/07conflict_avoid.t line 83.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 6.
t/classes/07conflict_avoid.t .......... Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 6/6 subtests
```

**Comment by mohawk2** [comment] 2015-07-19 11:13
Are you using the latest released version of ExtUtils::MakeMaker?

**Comment by ToApolytoXaos** [comment] 2015-07-19 12:13
Yes @mohawk2, if the question is for my issue, then yes, I use the latest available.

**Comment by mohawk2** [comment] 2015-07-19 14:38
@ToApolytoXaos Which C++ compiler are you using?

@daoswald The tests should probably use "skip" when can_ok $class, 'new' fails, I'll add that to my giant todo list :-)

**Comment by nanis** [comment] 2015-08-07 13:35
The problem is simply due to directory separators. Whenever you see messages like *Unrecognized escape ...*, assume you are inadvertently eval'ing or interpolating into a regex Windows style paths (e.g. `C:\Users\auser\somedirectory` etc).

I am working on a pull request and post on this. In the mean time, for more examples, see [Tests failing due to directory separators are unforced errors](http://www.nu42.com/2014/11/tests-failing-due-to-path-separators.html).

**Comment by ToApolytoXaos** [comment] 2015-08-17 03:11
I'm using Strawberry Perl 5.22 on Windows XP (VirtualBox) and the error message I got are these:
```
#   Failed test 'Foo::Bar::MyClass->can('new')'
#   at t/classes/07conflict_avoid.t line 71.
#     Foo::Bar::MyClass->can('new') failed

#   Failed test 'Foo::Bar::MyClass->new() died'
#   at t/classes/07conflict_avoid.t line 73.
#     Error was:  Can't locate object method "new" via package "Foo::Bar::MyClass" (perhaps you forgot to load "Foo::Bar::MyClass"?) at C:/Strawberry/perl/lib/Test/More.pm line 690.

#   Failed test 'Our "MyClass" is a "Foo::Bar::MyClass"'
#   at t/classes/07conflict_avoid.t line 75.
#          got: ''
#     expected: 'Foo::Bar::MyClass'

#   Failed test 'Foo::Qux::MyClass->can('new')'
#   at t/classes/07conflict_avoid.t line 77.
#     Foo::Qux::MyClass->can('new') failed

#   Failed test 'Foo::Qux::MyClass->new() died'
#   at t/classes/07conflict_avoid.t line 79.
#     Error was:  Can't locate object method "new" via package "Foo::Qux::MyClass" (perhaps you forgot to load "Foo::Qux::MyClass"?) at C:/Strawberry/perl/lib/Test/More.pm line 690.

#   Failed test 'Our "MyClass" is a "Foo::Qux::MyClass"'
#   at t/classes/07conflict_avoid.t line 81.
#          got: ''
#     expected: 'Foo::Qux::MyClass'
Can't call method "fetch" on an undefined value at t/classes/07conflict_avoid.t line 83.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 6.
```
The compiler I use is the one that comes with Strawberry Perl:
```
C:\>g++ --version
g++ (i686-posix-sjlj, built by strawberryperl.com project) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by bulk88** [comment] 2016-09-02 16:33
I believe this ticket is fixed by https://github.com/perl11/Inline-Filters/pull/3 so whenever a new I::F is released on CPAN this ticket will fixed. This failure is seen on CPANTesters BTW http://www.cpantesters.org/cpan/report/cc996ccd-6bf4-1014-9925-17d97ff97578  http://www.cpantesters.org/cpan/report/746e8f65-6c1e-1014-a87b-cf166a5d2e7b

**Comment by rurban** [comment] 2016-09-03 06:53
I'm just on holidays with no wifi. Will upload it on monday

**Comment by wbraswell** [comment] 2017-01-03 06:45
@bulk88 @rurban Great job on the release of Inline::Filters v0.18!
@stefanos82 
I have updated the latest RPerl code on GitHub (not CPAN) to require Inline::Filters v0.18, can you please test the latest RPerl code from GitHub and tell us if the problem is fixed?  Thanks!  :-)

**Comment by stefanos82** [comment] 2017-01-03 21:28
@wbraswell greetings mate. 

When I first attempted to compile it, I ran `cpanm rperl`. I have downloaded the repository locally and I'm trying to figure out how to compile the code. 

The instructions inside `INSTALL` are not clear at all about how to install it under Windows.

Let me see what I can do though.

As soon as I make it, I will come back with feedback.

Cheers.

**Comment by stefanos82** [comment] 2017-01-03 22:29
@wbraswell short reply: it hangs on `04_type_scalar.t ............................. 113/310`.

Long reply: I have figured out how to compile it, but it could have been simpler in my humble opinion.

Basically you have to run `perl Makefile.PL` first in order to generate a new `Makefile`.

On the first attempt it will report which modules are missing and you will have to manually install them yourself.

After you do so, you have to repeat the initial command to re-generate a new `Makefile` and run `dmake`. 

After a couple of seconds that finishes, you run `dmake test` and you can see it hanging on `04_type_scalar.t ............................. 113/310`.

```
Specs
-----
OS: Windows 7, 64-bit
Perl: strawberry-perl-5.24.0.1-64bit
```

**Comment by wbraswell** [comment] 2017-01-03 22:37
@stefanos82 
Please set the following environmental variables, then re-run the `dmake test` command.  Hopefully we will see some more useful output about where exactly it is hanging in t/04.

RPERL_VERBOSE=1
RPERL_DEBUG=1
TEST_VERBOSE=1

**Comment by stefanos82** [comment] 2017-01-04 01:40
@wbraswell There's an interesting message that flags you have suggested have revealed a problem that has to do with `t/03_inline_cpp.t`.

I don't know how it could be related to `t/04_type_scalar.t` though...anyway, here's the output:

```
C:\GIT_CODES\rperl>dmake test
"C:\Strawberry\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')" t/*.t
t/00_depend.t .................. # [[[ Beginning Dependency Tests ]]]
t/00_depend.t .................. ok
t/01_changes.t ................. # [[[ Beginning Change Log Tests ]]]
t/01_changes.t ................. ok
t/02_inline_c.t ................ # [[[ Beginning Inline::C Pre-Test Loading ]]]
# [[[ Beginning Selection Of Tests From The Inline::C Cookbook ]]]
t/02_inline_c.t ................ ok
t/03_inline_cpp.t .............. # [[[ Beginning Inline::CPP Pre-Test Loading ]]]
# [[[ Beginning Entirety Of Tests From The Inline::CPP POD ]]]
t/03_inline_cpp.t .............. 12/16 # [[[ MS Windows OS Detected, Inline::CPP Exception Temporarily Disabled, Skipping Elipses Revisited Part 4/4 Test, RPerl Inline System ]]]
t/03_inline_cpp.t .............. ok
t/04_type_scalar.t ............. [[[ BEGIN 'use Inline' STAGE for 'RPerl/HelperFunctions.cpp' ]]]
validate Stage
Starting Build Preprocess Stage
get_maps Stage
Finished Build Preprocess Stage

Starting Build Parse Stage
Finished Build Parse Stage

Starting Build Glue 1 Stage
Finished Build Glue 1 Stage

Starting Build Glue 2 Stage
Finished Build Glue 2 Stage

Starting Build Glue 3 Stage
Finished Build Glue 3 Stage

Starting Build Compile Stage
  Starting "perl Makefile.PL" Stage
  Finished "perl Makefile.PL" Stage

  Starting "make" Stage
  Finished "make" Stage

  Starting "make install" Stage
  Finished "make install" Stage

  Starting Cleaning Up Stage
  Finished Cleaning Up Stage

Finished Build Compile Stage

[[[ END   'use Inline' STAGE for 'RPerl/HelperFunctions.cpp' ]]]
# [[[ Beginning Scalar Type Pre-Test Loading, RPerl Type System ]]]
t/04_type_scalar.t ............. 1/? # [[[ Beginning RPerl Scalar Type Tests, PERL Operations & PERL Data Types ]]]
# [[[ Beginning RPerl Scalar Type Tests, CPP Operations & PERL Data Types ]]]
validate Stage
Starting Build Preprocess Stage
get_maps Stage
Finished Build Preprocess Stage

Starting Build Parse Stage
Finished Build Parse Stage

Starting Build Glue 1 Stage
Finished Build Glue 1 Stage

Starting Build Glue 2 Stage
Finished Build Glue 2 Stage

Starting Build Glue 3 Stage
Finished Build Glue 3 Stage

Starting Build Compile Stage
  Starting "perl Makefile.PL" Stage
  Finished "perl Makefile.PL" Stage

  Starting "make" Stage
  Finished "make" Stage

  Starting "make install" Stage
  Finished "make install" Stage

  Starting Cleaning Up Stage
  Finished Cleaning Up Stage

Finished Build Compile Stage

t/04_type_scalar.t ............. 105/? validate Stage
Starting Build Preprocess Stage
get_maps Stage
Finished Build Preprocess Stage

Starting Build Parse Stage
Finished Build Parse Stage

Starting Build Glue 1 Stage
Finished Build Glue 1 Stage

Starting Build Glue 2 Stage
Finished Build Glue 2 Stage

Starting Build Glue 3 Stage
Finished Build Glue 3 Stage

Starting Build Compile Stage
  Starting "perl Makefile.PL" Stage
  Finished "perl Makefile.PL" Stage

  Starting "make" Stage
  Finished "make" Stage

  Starting "make install" Stage
  Finished "make install" Stage

  Starting Cleaning Up Stage
  Finished Cleaning Up Stage

Finished Build Compile Stage

t/04_type_scalar.t ............. 109/? validate Stage
Starting Build Preprocess Stage
get_maps Stage
Finished Build Preprocess Stage

Starting Build Parse Stage
Finished Build Parse Stage

Starting Build Glue 1 Stage
Finished Build Glue 1 Stage

Starting Build Glue 2 Stage
Finished Build Glue 2 Stage

Starting Build Glue 3 Stage
Finished Build Glue 3 Stage

Starting Build Compile Stage
  Starting "perl Makefile.PL" Stage
  Finished "perl Makefile.PL" Stage

  Starting "make" Stage
  Finished "make" Stage

  Starting "make install" Stage
  Finished "make install" Stage

  Starting Cleaning Up Stage
  Finished Cleaning Up Stage

Finished Build Compile Stage

t/04_type_scalar.t ............. 113/?
```

**Comment by wbraswell** [comment] 2017-01-04 01:54
@stefanos82 
That message about t/03 skipping "elipses revisited" because of Windows is fine, @bulk88 and I put it there on purpose, that isn't a problem.  Unfortunately I don't see anything more helpful from your output.

Please make sure you have both of these environmental variables set:
RPERL_DEBUG=1
RPERL_VERBOSE=1

Then run `perl t/04_type_scalar.t' and see if it gives us any more output than it is giving now...

**Comment by stefanos82** [comment] 2017-01-04 02:03
This is what I get:

```
C:\GIT_CODES\rperl>perl t/04_type_scalar.t
Can't locate RPerl/AfterSubclass.pm in @INC (you may need to install the RPerl::AfterSubclass module) (@INC contains: C:/Strawberry/perl/site/lib/MSWin32-x64-multi-thread C:/Strawberry/perl/site/lib C:/Strawberry/perl/vendor/lib C:/Strawberry/perl/lib .) at t/04_type_scalar.t line 8.
BEGIN failed--compilation aborted at t/04_type_scalar.t line 8.
```

**Comment by wbraswell** [comment] 2017-01-04 02:05
You need to set your env var:
PERL5LIB=$PERL5LIB:lib
...
Can we use IRC?
irc.perl.org
#perl11

**Comment by mohawk2** [comment] 2017-01-04 02:21
`prove t/04_type_scalar.t`

**Comment by mohawk2** [comment] 2019-03-24 23:29
@wbraswell As far as you know, is this now fixed? I::F was updated ages ago, and @nanis made a PR for fixing this?

**Comment by mohawk2** [comment] 2019-03-25 03:20
If the new version (0.76) still has problems, please either reopen this or open a new issue.

**Closed by mohawk2** 2019-03-25 03:20 UTC

**Comment by wbraswell** [comment] 2019-04-01 17:14
@mohawk2 
What software exactly are you referring to as "0.76"?
I see Inline::CPP on metacpan is 0.75 and Inline::Filters is 0.20...

**Comment by mohawk2** [comment] 2019-04-01 17:27
Yes, I accidentally did an authorised release. You can still install 0.76 off backPAN with `cpanm Inline::CPP@0.77` (which is the slightly-updated one). Sorry for the confusion. The same question applies for 0.75 - is this still broken?

**Comment by wbraswell** [comment] 2019-04-01 17:29
@stefanos82 
Can you please check if this error still occurs on your computer using the latest versions of RPerl and Inline::CPP on CPAN?

**Comment by stefanos82** [comment] 2019-04-01 17:35
Unfortunately I don't use Windows as I don't have my original VM anymore...sorry.

**Comment by wbraswell** [comment] 2019-04-01 18:29
Okay we will leave this issue closed for now, unless we find more evidence of it existing under the new versions.
